# All the keys in this file are called from the code using i.e. Figaro.env.admin_user!

ADMIN_USER:
ADMIN_PASSWORD:
DEVISE_SECRET_KEY:
TRANSLOADIT_AUTH_KEY:
TRANSLOADIT_AUTH_SECRET:
TRANSLOADIT_TEMPLATES_S3_STORE:
ROLLBAR_ACCESS_TOKEN:
NEW_RELIC_LICENSE_KEY:

development:
  SECRET_KEY_BASE:
  FB_CLIENT_ID:
  FB_CLIENT_SECRET:

test:
  SECRET_KEY_BASE:
  FB_CLIENT_ID:
  FB_CLIENT_SECRET:

staging:
  SECRET_KEY_BASE:
  FB_CLIENT_ID:
  FB_CLIENT_SECRET:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_DIRECTORY:
  MANDRILL_USERNAME:
  MANDRILL_PASSWORD:

production:
  SECRET_KEY_BASE:
  FB_CLIENT_ID:
  FB_CLIENT_SECRET:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_DIRECTORY:
  TRANSLOADIT_AUTH_KEY:
  TRANSLOADIT_AUTH_SECRET:
  TRANSLOADIT_TEMPLATES_S3_STORE:
  MANDRILL_USERNAME:
  MANDRILL_PASSWORD:
